// tools/generateReactWithClaude.js
import fs from "fs";
import path from "path";
import Anthropic from "@anthropic-ai/sdk";
import "dotenv/config";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ---------- 1️⃣ Paths ----------
const appDir = path.resolve("./src");
const specPath = path.resolve("./data/uiSpec.json");

// ---------- 2️⃣ Check JSON ----------
if (!fs.existsSync(specPath)) {
  console.error("❌ uiSpec.json not found at:", specPath);
  process.exit(1);
}
const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));

// ---------- 3️⃣ Cleanup src folder ----------
/*function deleteFolderRecursive(folderPath) {
  if (!fs.existsSync(folderPath)) return;
  fs.readdirSync(folderPath).forEach((file) => {
    const curPath = path.join(folderPath, file);
    if (fs.lstatSync(curPath).isDirectory()) {
      deleteFolderRecursive(curPath);
    } else {
      fs.unlinkSync(curPath);
    }
  });
  fs.rmdirSync(folderPath);
}

if (fs.existsSync(appDir)) {
  console.log("🧹 Cleaning up previous src folder...");
  deleteFolderRecursive(appDir);
}
fs.mkdirSync(appDir, { recursive: true });*/

// ---------- 4️⃣ Prompt Claude ----------
const systemPrompt = `
You are a professional React developer.
Generate a full React app based on this flow JSON:
${JSON.stringify(spec)}

Requirements:
- React 18, React Router, Material UI
- main.jsx with routing
- Each page as a separate component
- Add placeholder text, images, cards, lists, dashboards where appropriate
- Make it visually appealing and realistic
- Ready to run in Vite or CRA
- Only provide React code files
- Do not use Node-only modules in the browser
`;

async function generateReactWithClaude() {
  try {
    console.log("🤖 Sending prompt to Claude...");

    const response = await client.messages.create({
      model: "claude-opus-4-20250514",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: "Generate the React app code now." },
      ],
      max_tokens_to_sample: 5000,
    });

    const rawCode = response.content[0].text;

    // Save the raw code; you can later split into multiple files if needed
    fs.writeFileSync(path.join(appDir, "GeneratedReact.jsx"), rawCode);
    console.log("✅ React code generated by Claude!");
  } catch (err) {
    console.error("❌ Error calling Claude API:", err);
  }
}

generateReactWithClaude();
